#
# Copyright 2017, SAP SE or an SAP affiliate company.
# All rights reserved.
#
---
<% require 'alti_chef_helpers' %>
<%= AltiChefHelpers.kitchen(platforms: '6.7') %>

suites:
  - name: default
    run_list:
      - recipe[alti_iproute2_app_test]
