driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6
  - name: centos-7
  - name: fedora-latest

suites:
  - name: default
    run_list:
      - recipe[interface_test]
