sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

branches:
  only:
    - master

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

env:
  matrix:
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7

before_script:
  - chef --version
  - cookstyle --version
  - foodcritic --version
